version: '3'
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes: 
      - mysql-data:/var/lib/mysql:delegated
    security_opt:
      - seccomp:unconfined
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/unicorn.pid && bundle exec unicorn -p 3000 -c /mountain_app/config/unicorn.rb"
    volumes: 
      - .:/mountain_app:delegated
      - tmp-data:/mountain_app/tmp/sockets:delegated
      - public-data:/mountain_app/public:delegated
    ports: 
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  nginx:
    build: 
      context:  ./nginx
      dockerfile: Dockerfile
    ports: 
      - "80:80"
    restart: always
    volumes: 
      - tmp-data:/mountain_app/tmp/sockets:delegated
      - public-data:/mountain_app/public:delegated
volumes: 
  mysql-data:
    driver: local
  tmp-data:
  public-data: