version: 2.1
executors: 
  test-executor: 
    docker:
      - image: cimg/ruby:2.6
        environment: 
          BUNDLE_PATH: vendor/bundle
          BUNDLER_VERSION: 2.1.4
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:8.0-ram
        environment: 
          MYSQL_USER: test-user
          MYSQL_DB: mountain_app_test
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
        command: mysqld --default-authentication-plugin=mysql_native_password
    working_directory: ~/mountain_app
jobs:
  test: 
    executor: test-executor
    steps: 
      - checkout
      - restore_cache:
          keys: 
            - v1-rails-bundle-{{ checksum "Gemfile.lock" }}
            - v1-rails-bundle-
      - run:
          name: gemの依存関係のインストール
          command: |
            sudo gem update --system
            bundle config set path 'vendor/bundle'
            bundle check || bundle install
      - save_cache:
          key: v1-rails-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: データベースの起動を待機
          command: |
            dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load --trace
      - run:
          name: Rspceテスト
          command: bin/rspec   
  deploy:
    machine: 
      image: circleci/classic:edge
    steps:
      - checkout
      - add_ssh_keys:
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "cd /home/ec2-user/mountain_app && git pull origin master"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: 
                - master
