default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") {'db'} %>
  username: root
  password: password

development:
  <<: *default
  database: mountain_app_development

test:
  <<: *default
  database: mountain_app_test

production:
  <<: *default
  database: mountain_app_production
  # username: <%= ENV['DB_USERNAME'] %>
  # password: <%= ENV['DB_PASSWORD'] %>

  # host: RDSのエンドポイントを設定
  # 定義はECSのタスク定義の環境変数